### ISSUE TITLE
Provide a variable to allow integration with consult?

### ISSUE THREAD

**Issue by bdwalton** [davep/goto-line-faster.el#2]
Wondering if you'd be willing to provide a goto-line-faster-goto-function variable that allows users of the package to define the interactively invoked function? I'd like to invoke consult-goto-line, for example so that I leverage consult's functionality.

**Comment by davep** [comment]
I'm afraid I don't know consult do can't really follow what any of that would mean; but sure, if making the function that's called configurable would be helpful I'm happy to add that.

**Comment by bdwalton** [comment]
Cool. I'm only switching my config to consult now, so I'd be happy to work
up a patch and verify it works with consult, then send it over.

**Comment by davep** [comment]
Quickly added this and merged it into `main`. I think this was the idea, yeah? (#3)

**Comment by bdwalton** [comment]
Yep, that looks perfect. I'll give it a whirl in the next few days and let
you know for sure.

**Comment by bdwalton** [comment]
This works perfectly. I now add

```
:init
(setq goto-line-faster-goto-line-function #'consult-goto-line)
```

in the use-package for goto-line-faster and get the benfits of the nicer functionality.

Thanks!

**Comment by davep** [comment]
Cool! Glad to hear it works! The way I've done it I think this should work in the `use-package` too:

```elisp
:custom (goto-line-faster-goto-line-function #'consult-goto-line)
```
